plugins:
  - jekyll-multiple-languages-plugin

safe: true

whitelist:
  - jekyll-multiple-languages-plugin

plugins:
  - jekyll-multiple-languages-plugin

languages: ["fr","en"]
exclude_from_localizations: ["assets"]

languageNames:
  fr: Français
  en: English